language: node_js
node_js:
- '6.9'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: IfAg7RYcHODI/6bPVYXDkJB8YxC7gAvhsipuRFsBWEoI6WiNLpUvHyg9IcHgfxwV1gWWiE3Mevqqi0dUL35g2ogoFzNtsFtf1n244BMe2kI42cAGGGwZED6+jNv352v+vvnZ6R9Yx7rRwbizWJIyc9q6rhZyqWf0snb3VjFTwYFKkvgAhOwr3ePK6XAJTt6ej+d/BLV8KZS4KdFnoX3GZeg8MdQZEnBVkLuL5te6+Ip9BwLLBO2N6CjW3ACt3E6BQRNIJ1HeSMp/kDHeEr3mEejP11Xdr33R4CjrFhjfU9aIobftDZ8yH1lb5xUl/l1nFGp9i9Mgqg8VTTxTTqY8sWZtBHbSxeHsUSRi6aMfjh/w2LVJ4nW+b8D14ujEpatBNUrvCXS8YbcaH1AJvpARcf/xzZ+rFt57xuMDW5MaPqp2dzQwSUj7R1tUd9C+0VDLfmJHybqMuitqZczoOXCapMmTl5uOkDKIvyFMkVQ+/K3hBTjpqSks20CeT01AwgCOH9SDnBDc+2Ml/mGKU/NaDt01UemTpb+5RlY5RjwxVlu7XXGbaSfAGilNikYCEcGYnVhl8rPwFk9n5gakg8OAnWzB1Q354nvzYiaGQzSb67um5dF/4Yd3UC1QnzG2oKmWrHgL3BvklJvGrXoouxQzFGVAM5qY315PjlssjRTxKG4=
  app: robo-tope
  on:
    repo: princiweb/robo_tope
