language: node_js
node_js:
- '0.10'
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: BQgLwJ6NYbiI5X9M6BQvp0dcx7SP1897YIIrBAYnrxOMXaqN8RBquxWBdYctjfvboT1rY7JiZBpTmRMhDLpKJLMjP+n0l3cFKkaCmum0BjXLxD4oXGXnVKsIJ/zA1dAnulk/6jN8cAs3zGusn3LSMVwxX/DSX99HEwKfPEd7xbQZrJ0gnEyBChXsESmALJQxEuS5iOaZ4q42yxl+PyMkkPM7ZtUzrvl51Ugv2HoHgiNr0qaD9yt1X3W6QHCD6C5nNmDy3k5ZlI3TnkoS5uTzLwtnNOip26U6uo/g3N6QielRYUAtNDb/2CdAJcXuBzkTggDEDdNi2YVO9W3F4VHPZxjpObM9CWNWBa1qaLMTEGHO/KNjk1spuqMyTofUiIAYzmBajpJWM4+bgQHkbdRqGaPAf9BqnCzVn0Qd5DiYvv4XxVSprYsYetQL5e9Zt03zRwf3ukESnNYCQ3ETkRF0sv3pjSbc3mW7bbFqtTL8rhqvZDcRUOIxDhJCtfP8cJThsHRDZvgpSHlLGP5fZDKJyMbp0FbyEVG5GqEX3wnhtBdsAhg0uRaf6QApn+ua9jtPWq7MtFYkTFsFupOrzGIjx7x9+wuZrdT8F7S2xF+VQGhvrdpkbA+kDLoefjInbm9bLD4adteS6SczxUNDcZID4Kwsl6aXmz/y16TQWe2cemc=
